targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/domain/models/**.dart
            - lib/data/models/dtos/**.dart
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/domain/models/**.dart
            - lib/data/models/dtos/**.dart
      drift_dev:
        generate_for:
          include:
            - lib/data/datasources/local/**.dart